name: Build & Check
on: [pull_request, push]
jobs:
  check:
    name: Run Gradle checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Run checks
        run: ./gradlew check --rerun-tasks
